apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: xxl-job-agent-exec
rules:
  - apiGroups:
      - ""
    resources:
      - 'pods/exec'
    verbs:
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: xxl-job-agent-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: xxl-job-agent-exec
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default

